### ISSUE TITLE
0.9.0/0.9.1 don't build with Swift 5.0.x

### ISSUE THREAD

**Issue by kengruven** [iwasrobbed/Down#217]
Please help prevent duplicate issues before submitting a new one:

* [X] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

The Cartfile of my project used to have the line:

    github "iwasrobbed/Down" == 0.8.6

I want to try out a feature that's in the 0.9.x series, and I see in the README that 0.9.2+ is for Swift 5.1 (which I don't have), so I changed this line to:

    github "iwasrobbed/Down" == 0.9.1

and ran:

    carthage update --no-use-binaries --platform Mac Down

## What did you expect to happen?

I expected version 0.9.1 to be built, and to appear in Carthage/Build/Mac/Down.framework.

## What happened instead?

I got a compilation error:

    .../Carthage/Checkouts/Down/Source/AST/Styling/Stylers/DownStyler.swift:38:71: error: type of expression is ambiguous without more context
        private var listPrefixAttributes: [NSAttributedString.Key : Any] {[
                                                                          ^

Looking at [the code](https://github.com/iwasrobbed/Down/blob/v0.9.1/Source/AST/Styling/Stylers/DownStyler.swift#L38-L41), this appears to be using [a new Swift 5.1 language feature](https://swift.org/blog/swift-5-1-released/), even though it was added to Down in the 5.0-compatible era (0.9.0 / 0.9.1).

How hard would it be to add one word (`return`) here?

**Comment by kengruven** [comment]
I forked and branched (from tag "v0.9.1") with 2 small changes, and this builds with Swift 5.0.1 again:

https://github.com/iwasrobbed/Down/compare/master...kengruven:swift50

**Comment by iwasrobbed** [comment]
Hi @kengruven 👋 You're welcome to maintain your fork, but I'd rather not backport changes to prior Swift versions. It's a rabbit hole that only benefits a few people versus the maintainers having to keep a mental model of all these extra changes

**Comment by kengruven** [comment]
That's fair.  Can we at least update the README?

**Comment by iwasrobbed** [comment]
@kengruven Done here https://github.com/iwasrobbed/Down/commit/296ad5409a3280574df17b47db06af5ab4226068

Thanks for pointing it out
