### PR TITLE
[SPM] Fixes error with missing headers

### LINKED ISSUE #151: Can't build with Swift 5.1 with SwiftPM
# Report

## What did you do?

1. Clone Down
2. `xcode-select` Xcode 11 beta 1
3. `swift build`

## What did you expect to happen?

It should build.

## What happened instead?

```
» swift build
In file included from /Users/mdiep/Repositories/iwasrobbed/Down/Source/cmark/scanners.c:3:
In file included from /Users/mdiep/Repositories/iwasrobbed/Down/Source/cmark/chunk.h:7:
/Users/mdiep/Repositories/iwasrobbed/Down/Source/cmark/cmark.h:5:10: error: 'cmark_export.h' file not found with <angled> include; use "quotes" instead
#include <cmark_export.h>
         ^~~~~~~~~~~~~~~~
         "cmark_export.h"
/Users/mdiep/Repositories/iwasrobbed/Down/Source/cmark/cmark.h:6:10: error: 'cmark_version.h' file not found with <angled> include; use "quotes" instead
#include <cmark_version.h>
         ^~~~~~~~~~~~~~~~~
         "cmark_version.h"
.
[0/19] Compiling libcmark xml.c
```

This also affects building Down as a SwiftPM package using the new support in Xcode 11.

### PR DESCRIPTION
**Pull request by aasimk2000**
This fixes #151 

It was solved by adding the cmark directory into the publicHeadersPath. The include directory had to be excluded to avoid SPM conflicts with include paths.

### CODE REVIEW

**Comment by iwasrobbed** [comment]
Thanks @aasimk2000 👍 I'd like @mdiep to review if possible

**Comment by robb** [comment]
Yeah, can confirm.

**Comment by iwasrobbed** [comment]
Thanks @aasimk2000, @mdiep and @robb 🙌
